"""Export a saved plan as a downloadable JSON document or a readable text report."""

import json

from ai_engine.options import label
from backend.models.schemas import PlanOut

MEAL_ORDER = ("breakfast", "lunch", "snack", "dinner")

EXPORT_MEDIA_TYPES = {
    "json": "application/json",
    "txt": "text/plain; charset=utf-8",
}


def export_filename(plan: PlanOut, extension: str) -> str:
    return f"diet-plan-{plan.created_at:%Y-%m-%d}-{plan.id[:8]}.{extension}"


def plan_to_json(plan: PlanOut) -> bytes:
    return json.dumps(plan.model_dump(mode="json"), indent=2, ensure_ascii=False).encode("utf-8")


def _engine_description(plan: PlanOut) -> str:
    if plan.source == "ai":
        return f"AI provider ({plan.ai_provider}, model {plan.ai_model})"
    text = "Rule-based recommendation engine"
    if plan.fallback_reason:
        text += f" (AI fallback: {plan.fallback_reason})"
    return text


def plan_to_text(plan: PlanOut) -> str:
    summary = plan.nutrition_summary
    targets, totals = summary.targets, summary.totals
    allergies = ", ".join(label(a) for a in plan.allergies) or "none"
    lines = [
        "AI-Powered Personal Diet Planner: Diet Plan",
        "=" * 44,
        f"Title:              {plan.title}",
        f"Created:            {plan.created_at:%Y-%m-%d %H:%M} UTC",
        f"Generated by:       {_engine_description(plan)}",
        f"Dietary preference: {label(plan.dietary_preference)}",
        f"Goal:               {label(plan.goal)}",
        f"Cuisine:            {label(plan.cuisine)}",
        f"Allergies:          {allergies}",
        "",
        f"Daily target: {targets.calories:,} kcal | protein {targets.protein_g} g | "
        f"carbs {targets.carbs_g} g | fat {targets.fat_g} g",
        f"Plan total:   {totals.calories:,} kcal | protein {totals.protein_g} g | "
        f"carbs {totals.carbs_g} g | fat {totals.fat_g} g | fibre {totals.fiber_g} g",
        "",
    ]
    for slot in MEAL_ORDER:
        meal = getattr(plan, slot)
        lines += [
            f"{slot.upper()}: {meal.name}",
            f"  Portion:     {meal.servings:g} x {meal.portion}",
            f"  Nutrition:   {meal.calories} kcal | P {meal.protein_g} g | C {meal.carbs_g} g | "
            f"F {meal.fat_g} g | fibre {meal.fiber_g} g",
            f"  Ingredients: {', '.join(meal.ingredients)}",
        ]
        if meal.why:
            lines.append(f"  Why:         {meal.why}")
        lines.append("")
    lines += ["HYDRATION", f"  {plan.hydration_tip}", "", "TIPS"]
    lines += [f"  - {tip}" for tip in plan.tips]
    lines += ["", "DISCLAIMER", f"  {plan.disclaimer}", ""]
    return "\n".join(lines)
